version: '3'
services:
  crawler-web:
    image: nginx
    container_name: crawler-web
    restart: always
    ports:
      - 8091:8091
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    links:
      - crawler-php

  crawler-php:
    image: php:7.1.15-fpm
    container_name: crawler-php
    ports:
      - 9005:9005
    restart: always
    volumes:
      - ./app:/var/www/html
